# Generated by Django 2.1 on 2019-11-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=30)),
                ('statecode', models.IntegerField()),
                ('state_cm', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
